project:
  type: website

website:
  title: "Dr. U"
  image: umairlogo2.png
  favicon: umair-profile1.jpg
  twitter-card:
    creator: "@umairdurrani87"
  open-graph: true
  site-url: https://umairdurrani.com/
  navbar:
    background: "#f0eeeb"
    logo: umairlogo2.png
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Talks
      - href: https://scholar.google.com/citations?user=jS1b6osAAAAJ&hl=en
        target: _blank
        text: Publications
      - href: MLinTransportation.qmd
        text: ML
      - href: blog.qmd
        text: Blog
      - text: "More"
        menu:
        - text: "Segmented"
          href: https://umair.shinyapps.io/segmented_app_doc/
          target: _blank
        - text: "R for Driving Sim"
          href: https://umair.shinyapps.io/R_for_driving_sim/
          target: _blank
        - text: "Ontario Weather Dashboard"
          href: https://rpubs.com/durraniu/on_dashboard
          target: _blank
        - text: "Interactive Plotting in R"
          href: https://rpubs.com/durraniu/interactive_plots
          target: _blank
        - text: "Histogram y axis"
          href: https://rpubs.com/durraniu/sovg
          target: _blank
        - text: "Decision Tree Example"
          href: https://rpubs.com/durraniu/DTQR
          target: _blank
        - text: "BBC 100 Women"
          href: https://durraniu.github.io/BBC100/
          target: _blank
    right:
      - icon: github
        href: https://github.com/durraniu
        target: _blank
      - icon: twitter
        href: https://twitter.com/umairdurrani87
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/durraniu/
        target: _blank


format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
    

execute: 
  freeze: true
