project:
  type: website

website:
  title: "Umair Durrani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects
      - href: software.qmd
        text: Software
      - href: https://scholar.google.com/citations?user=jS1b6osAAAAJ&hl=en
        text: Publications
      - href: MLinTransportation.qmd
        text: ML
      - href: blog.qmd
        text: Blog
      - text: "Fun R Stuff"
        menu:
        - text: "Segmented"
          href: https://umair.shinyapps.io/segmented_app_doc/
        - text: "R for Driving Sim"
          href: https://umair.shinyapps.io/R_for_driving_sim/
        - text: "Ontario Weather Dashboard"
          href: https://rpubs.com/durraniu/on_dashboard
        - text: "Short Intro. to Data Science"
          href: https://rpubs.com/durraniu/datavizr
        - text: "Short Intro. to ggplot2"
          href: https://github.com/durraniu/ggplot2_for_beginners/blob/master/Using_ggplot2.Rmd
        - text: "Interactive Plotting in R"
          href: https://rpubs.com/durraniu/interactive_plots
        - text: "Histogram y axis"
          href: https://rpubs.com/durraniu/sovg
        - text: "Decision Tree Example"
          href: https://rpubs.com/durraniu/DTQR
        - text: "BBC 100 Women"
          href: https://durraniu.github.io/BBC100/
        - text: "Hypothesis Test for Population Mean"
          href: https://rpubs.com/durraniu/HT1
    right:
      - href: CV.pdf
        text: CV
      - icon: github
        href: https://github.com/durraniu
      - icon: twitter
        href: https://twitter.com/umairdurrani87
      - icon: linkedin
        href: https://www.linkedin.com/in/durraniu/


format:
  html:
    theme:
      - journal
      - theme.scss
    css: 
      - styles.css
      - academicons.css
    toc: true
    

execute: 
  freeze: auto
