project:
  type: website

website:
  title: "Dr. U"
  image: umairlogo2.png
  favicon: umair-profile1.jpg
  twitter-card:
    creator: "@umairdurrani87"
  open-graph: true
  site-url: https://umairdurrani.com/
  navbar:
    background: "#f0eeeb"
    logo: umairlogo2.png
    title: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Training
      - href: https://scholar.google.com/citations?user=jS1b6osAAAAJ&hl=en
        text: Publications
      - href: MLinTransportation.qmd
        text: ML
      - href: blog.qmd
        text: Blog
      - href: resume_linkedin.pdf
        text: Resume
      - text: "More"
        menu:
        - text: "Segmented"
          href: https://umair.shinyapps.io/segmented_app_doc/
        - text: "R for Driving Sim"
          href: https://umair.shinyapps.io/R_for_driving_sim/
        - text: "Ontario Weather Dashboard"
          href: https://rpubs.com/durraniu/on_dashboard
        - text: "Short Intro. to Data Science"
          href: https://rpubs.com/durraniu/datavizr
        - text: "Short Intro. to ggplot2"
          href: https://github.com/durraniu/ggplot2_for_beginners/blob/master/Using_ggplot2.Rmd
        - text: "Interactive Plotting in R"
          href: https://rpubs.com/durraniu/interactive_plots
        - text: "Histogram y axis"
          href: https://rpubs.com/durraniu/sovg
        - text: "Decision Tree Example"
          href: https://rpubs.com/durraniu/DTQR
        - text: "BBC 100 Women"
          href: https://durraniu.github.io/BBC100/
        - text: "Hypothesis Test for Population Mean"
          href: https://rpubs.com/durraniu/HT1
    right:
      - icon: github
        href: https://github.com/durraniu
      - icon: twitter
        href: https://twitter.com/umairdurrani87
      - icon: linkedin
        href: https://www.linkedin.com/in/durraniu/


format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
    

execute: 
  freeze: auto
